### ISSUE TITLE
Geeup cookie_setup - SyntaxError

### ISSUE THREAD

**Issue by SdeRodaHusman** [samapriya/geeup#36] opened 2021-05-18 14:51 UTC
Dear @samapriya,

Thanks again for the great tool! I have a small issue with the Cookie Setup method and was wondering if you had any idea on what I could be doing wrong? I used the cookie-method before to upload my data to GEE, and then it worked perfectly. Today, the cookies were expired, so I wanted to update them.

However, when I typed `geeup cookie_setup` and entered the cookie string, I received the message `Cookie Setup completed`. After that, I wanted to upload my data using `geeup upload`, but then I got the message `Cookies Expired | Enter your Cookie List:  `. I don't really understand this, because I just completed the Cookie Setup. Nevertheless, I tried to enter my cookie string once again, but then I received the following error:

```
Traceback (most recent call last):
  File "/net/labdata/sophiedrh/Environments/GEE/bin/geeup", line 8, in <module>
    sys.exit(main())
  File "/net/labdata/sophiedrh/Environments/GEE/lib/python3.5/site-packages/geeup/geeup.py", line 602, in main
    func(args)
  File "/net/labdata/sophiedrh/Environments/GEE/lib/python3.5/site-packages/geeup/geeup.py", line 313, in upload_from_parser
    pyramiding=args.pyramids,
  File "/net/labdata/sophiedrh/Environments/GEE/lib/python3.5/site-packages/geeup/batch_uploader.py", line 101, in upload
    google_session = __get_google_auth_session(user, password, method)
  File "/net/labdata/sophiedrh/Environments/GEE/lib/python3.5/site-packages/geeup/batch_uploader.py", line 373, in __get_google_auth_session
    and ast.literal_eval(response.text)["url"] is not None
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

Do you have any idea about what could be going wrong? Thank you very much in advance!

All the best,
Sophie

**Comment by samapriya** [comment] 2021-05-19 04:40
I have tested this on both Linux and a windows machine and both work for me, I am hoping you are running the latest version of geeup. Could I recommend you open code.earthengine.google.com using a new incognito window and then copy the cookies and paste it. It might have been an intermittent issue because I have been unable to reproduce it.

**Comment by samapriya** [comment] 2021-05-21 12:40
Hey @SdeRodaHusman 
Let me know if you have any updates on this or got it to work.

**Comment by SdeRodaHusman** [comment] 2021-05-21 13:39
Hi @samapriya! 

Thanks for the advice. The cookie method is working now :) I got it to work by saving the cookies from a "normal" Google window, instead of an incognito window. I don't know why, but this worked! 

Thanks again!

**Comment by samapriya** [comment] 2021-05-21 13:58
Very interesting thanks for reporting back , I will close the issue for now then :)

**Closed as completed** 2021-05-21 13:58 UTC

**Comment by samapriya** [comment] 2021-05-24 05:04
Just as a follow-up it made sense that it did not work in incognito mode. Turns out incognito mode turns off certain cookies to prevent tracking among other things so yeah the cookies should only be copied form the main session. Thought it was interesting enough to note so noting it here
