### ISSUE TITLE
invalid syntax (<unknown>, line 2)

### ISSUE THREAD

**Issue by N-Acil** [samapriya/geeup#15] opened 2019-12-17 11:59 UTC
Hi @samapriya,

I am trying to batch upload a number of zipped shapefiles using `geeup seltabup`, but I get the error: `invalid syntax (<unknown>, line 2)` 

The command I am trying to run is:
`geeup seltabup --dest users/MyUsername/Project/Test -u MyUsername@gmail.com --source "C:\Conda4\envs\ee\Test\ZIP"` 

It could create my folder `Test` in GEE. But once it reaches the upload part, I keep receiving the same error in both Windows 10 and Ubuntu machines. I have updated the package with `geeup init` and could successfully zip the shapefiles with `geeup zipshape`. 2fa and apps are turned off.

Could you please check what is wrong?

Thank you

**Comment by samapriya** [comment] 2019-12-17 14:46
Hi @N-Acil 
Can you attach a few of the zip files to test? Might be an intermittent issue but having a few of the zip files will allow for testing

**Comment by N-Acil** [comment] 2019-12-17 15:21
Thanks for the quick reply. Attached one of the zip files. The polygons represent patches of forest loss in 2018. 
[51P_UTM_30m_2018_pid_lsm.zip](https://github.com/samapriya/geeup/files/3974006/51P_UTM_30m_2018_pid_lsm.zip)

**Comment by samapriya** [comment] 2019-12-17 15:56
Hey @N-Acil 
It seems to be working at my end: I uploaded and tested it. Here is the [earthengine script](https://code.earthengine.google.com/177189ade377d1181027d424ba4467db)

Could you also try putting the dest argument inside double quotes, because "Windows" escapes paths when using slashes so something like 

```
geeup seltabup --dest "users/MyUsername/Project/Test" -u "MyUsername@gmail.com" --source "C:\Conda4\envs\ee\Test\ZIP"
```

**Comment by N-Acil** [comment] 2019-12-17 16:49
Same problem with the double quotes... I have also tried in Ubuntu with `geeup seltabup --dest users/MyUsername/Project/Test -u MyUsername@gmail.com --source /home/MyUsername/Test/ZIP`

Good to know there is no issues with the shapefiles. Thanks.

**Comment by samapriya** [comment] 2019-12-17 17:03
Unfortunately, I cannot reproduce the problem at my end. I was able to upload the zip file you sent using ```geeup seltabup``` on a windows machine. So at this point, the tool seems to be working at my end, but I wonder if there is something going on the google account.

Can you try the ```geeup selsetup``` tool as a last resort? This allows for setting up and making sure the flow is correct for your selenium driver while connecting to your earth engine account. I would recommend you try it on your windows machine first and then switch to Ubuntu

**Comment by samapriya** [comment] 2019-12-18 02:34
Since I cannot recreate this issue and have no additional way to resolve this I am closing this issue for now.

**Closed as completed by samapriya** 2019-12-18 02:34 UTC

**Comment by jkittner** [comment] 2020-07-08 02:46
Hey N-Acil,
I just came about this issue today as well. It is caused by [this line](https://github.com/samapriya/geeup/blob/55cab11223f9636e6052392b4d0de816c90ade1b/geeup/sel_tuploader.py#L112) and is most likely due to a failed authentication. A `json` is expected but when the authetication failed an HTML is returned which cannot be parsed.

It would be helpful to return the whole stacktrace. You might consider using the `tracback` module here.
```
>>> import requests
>>> import ast
>>> r = requests.get('https://code.earthengine.google.com/assets/upload/geturl')
>>> ast.literal_eval(r.text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jk\AppData\Local\Programs\Python\Python37\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\jk\AppData\Local\Programs\Python\Python37\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

The failed authentication is most likely due to a missing two factor authentication. You can check what's going on by uncommenting [this line](https://github.com/samapriya/geeup/blob/55cab11223f9636e6052392b4d0de816c90ade1b/geeup/sel_tuploader.py#L71).
The function does not check if the authentication was completely successfull. When there were no errors finding the right buttons it just `time.sleep(5)` calls the earth engine website sleeps for another 8 seconds and continues. When it tries to fetch the link to upload your file, google does not return the expected `json` because the user is not authenticated.

**Comment by samapriya** [comment] 2020-07-08 12:44
This tool does not handle two-factor authentication in any way. But I have introduced a method to check if the session is authenticated so it provides better error parsing.
